In [26]:
import numpy as np 
from scipy.linalg import svd 

The line import numpy as np imports the numpy library and assigns it the alias np. This allows you to use various numerical and array operations provided by NumPy.

The line from scipy.linalg import svd imports the svd function from the scipy.linalg module. The svd function is a high-level implementation of the Singular Value Decomposition algorithm.

In [27]:
#This function calculates the Eigenvectors corresponding for U matrice
def calculU(M): 
    newM = np.dot(M, M.T) 
        
    eigenvalues, eigenvectors = np.linalg.eig(newM) 
    ncols = np.argsort(eigenvalues)[::-1] 
    
    return eigenvectors[:,ncols] 

This function takes a matrix M as input. It first computes newM by performing the dot product between M and its transpose using np.dot(M, M.T).

Next, it calculates the eigenvalues and eigenvectors of newM using np.linalg.eig. The eigenvalues and eigenvectors variables store the eigenvalues and corresponding eigenvectors, respectively.

The line ncols = np.argsort(eigenvalues)[::-1] sorts the eigenvalues in descending order and stores the corresponding indices in ncols. This step ensures that the eigenvectors are arranged in the correct order.

Finally, the function returns the eigenvectors corresponding to the sorted eigenvalues by using the [:, ncols] indexing. This ensures that the returned eigenvectors maintain the same order as the sorted eigenvalues.

In [28]:
#This function calculates the Eigenvectors corresponding for V matrice
def calculVt(M): 
    newM = np.dot(M.T, M)
        
    eigenvalues, eigenvectors = np.linalg.eig(newM) 
    ncols = np.argsort(eigenvalues)[::-1] 
    
    return eigenvectors[:,ncols].T 


This function takes a matrix M as input. It begins by comparing the sizes of the matrices np.dot(M, M.T) and np.dot(M.T, M) using np.size. If the former is larger, it calculates newM as the dot product of M.T and M, otherwise as the dot product of M and M.T. This ensures that newM corresponds to the matrix used for the calculation of singular values.

Next, it computes the eigenvalues and eigenvectors of newM using np.linalg.eig. The eigenvalues and eigenvectors variables store the resulting eigenvalues and corresponding eigenvectors, respectively.

The line eigenvalues = np.sqrt(eigenvalues) takes the square root of each eigenvalue, as singular values are typically obtained by taking the square root of eigenvalues in the SVD.

Finally, the function returns the eigenvalues in descending order using eigenvalues[::-1]. This step ensures that the eigenvalues are sorted in the same order as the SVD implementation.

In [29]:
#Function that calculates Eigenvalues corresponding to the Sigma Matrix 
def calculSigma(M): 
    if (np.size(np.dot(M, M.T)) > np.size(np.dot(M.T, M))): 
        newM = np.dot(M.T, M) 
    else: 
        newM = np.dot(M, M.T) 
        
    eigenvalues, eigenvectors = np.linalg.eig(newM) 
    eigenvalues = np.sqrt(eigenvalues) 
    #Sorting in descending order as the svd function does 
    return eigenvalues[::-1] 

This function takes a matrix M as input. It starts by comparing the sizes of the matrices np.dot(M, M.T) and np.dot(M.T, M) using np.size. If the former is larger, it calculates newM as the dot product of M.T and M, otherwise as the dot product of M and M.T. This step determines the appropriate matrix for eigenvalue calculation.

Next, it computes the eigenvalues and eigenvectors of newM using np.linalg.eig. The eigenvalues and eigenvectors variables store the resulting eigenvalues and corresponding eigenvectors, respectively.

The line eigenvalues = np.sqrt(eigenvalues) takes the square root of each eigenvalue since singular values are typically obtained by taking the square root of eigenvalues in the SVD.

Finally, the function returns the eigenvalues in descending order using eigenvalues[::-1]. This ensures that the eigenvalues are sorted in the same order as the SVD implementation.

In [30]:
#Creating our matrix 
A = np.array([[4,2,0],[1,5,6]])

In [32]:
#Calling the corresponding Fuctions and saving the values in variables 
U = calculU(A) 
Sigma = calculSigma(A) 
Vt = calculVt(A)

In [33]:
print("-------------------U-------------------")
print(U)
print("\n--------------Sigma----------------")
print(Sigma)
print("\n-------------V transpose---------------")
print(Vt)

-------------------U-------------------
[[-0.28978415 -0.95709203]
 [-0.95709203  0.28978415]]

--------------Sigma----------------
[8.13872588 3.97003036]

-------------V transpose---------------
[[-0.26001965 -0.65919758 -0.70558368]
 [-0.89132415 -0.11719389  0.43795758]
 [ 0.37139068 -0.74278135  0.55708601]]


In [34]:
#Checking if we can remake the original matrix using U,Sigma,Vt

newSigma = np.zeros((2, 3))
newSigma[:2, :2] = np.diag(Sigma[:2])

print(A,"\n")

A_remake = (U @ newSigma @ Vt)
print(A_remake)

[[4 2 0]
 [1 5 6]] 

[[4.00000000e+00 2.00000000e+00 2.22044605e-16]
 [1.00000000e+00 5.00000000e+00 6.00000000e+00]]
