In [38]:
import numpy as np

In [ ]:
#Creating a matrix A
A = np.array([[4,2,0],[1,5,6]])

In [ ]:
#Performing SVD
U, Sigma, Vt = np.linalg.svd(A)

The np.linalg.svd function calculates the SVD of the matrix A. The function returns three outputs: U, Sigma, and Vt.

U is a unitary matrix (orthogonal in the real case) representing the left singular vectors of A. It has shape (m, m) if A is an m x n matrix.
Sigma is a 1-dimensional array containing the singular values of A. The singular values are sorted in descending order.
Vt is a unitary matrix (orthogonal in the real case) representing the right singular vectors of A. It has shape (n, n) if A is an m x n matrix.
By assigning the outputs of np.linalg.svd(A) to U, Sigma, and Vt, you obtain the calculated singular vectors and singular values of A.

In [39]:
print("-------------------U-------------------")
print(U)
print("\n--------------Sigma----------------")
print(Sigma)
print("\n-------------V transpose---------------")
print(Vt)

-------------------U-------------------
[[ 0.28978415 -0.95709203]
 [ 0.95709203  0.28978415]]

--------------Sigma----------------
[8.13872588 3.97003036]

-------------V transpose---------------
[[ 0.26001965  0.65919758  0.70558368]
 [-0.89132415 -0.11719389  0.43795758]
 [ 0.37139068 -0.74278135  0.55708601]]


In [40]:
#Checking if we can remake the original matrix using U, Sigma, Vt

newSigma = np.zeros((2, 3))
newSigma[:2, :2] = np.diag(Sigma[:2])

print(A,"\n")

A_remake = (U @ newSigma @ Vt)
print(A_remake)

[[4 2 0]
 [1 5 6]] 

[[ 4.00000000e+00  2.00000000e+00 -2.22044605e-16]
 [ 1.00000000e+00  5.00000000e+00  6.00000000e+00]]
